import { Express } from "express";
import { statusRouter } from "./status";
import { logsRouter } from "./logs";
import { knowledgeRouter } from "./knowledge";
import { clarificationsRouter } from "./clarifications";
import { loreGapsRouter } from "./lore-gaps";
import { settingsRouter } from "./settings";
import { providersRouter } from "./providers";
import { keysRouter } from "./keys";
import { discordRouter } from "./discord";
import { modelsRouter } from "./models";
import { openrouterRouter } from "./openrouter";
import { claudeCodeRouter } from "./claude-code";
import { obsidianRouter } from "./obsidian";
import { modelProbeRouter } from "./model-probe";
import { forgeRouter } from "./forge";
import { diagnosticsRouter } from "./diagnostics";
import { integrationsRouter } from "./integrations";
import { updatesRouter } from "./updates";
import { devCredentialRouter } from "./dev-credential";
import { personasRouter } from "./personas";
import { docsRouter } from "./docs";
import { mcpApiRouter } from "./mcp";
import { mcpRouter } from "../mcp/server";

export function registerRoutes(app: Express): void {
  app.use(statusRouter);
  app.use(logsRouter);
  app.use(knowledgeRouter);
  app.use(clarificationsRouter);
  app.use(loreGapsRouter);
  app.use(settingsRouter);
  app.use(providersRouter);
  app.use(keysRouter);
  app.use(discordRouter);
  app.use(modelsRouter);
  app.use(openrouterRouter);
  app.use(claudeCodeRouter);
  app.use(obsidianRouter);
  app.use(modelProbeRouter);
  app.use(forgeRouter);
  app.use(diagnosticsRouter);
  app.use(integrationsRouter);
  app.use(updatesRouter);
  app.use(devCredentialRouter);
  app.use(personasRouter);
  app.use(docsRouter);
  app.use(mcpApiRouter);
  app.use(mcpRouter);
}
